### ISSUE TITLE
Multiline description falsely identified as "too short"

### ISSUE THREAD

**Issue by phantinuss** [humpalum/vscode-sigma#1]
Description is too short. Please elaborate(sigma_DescTooShort)
![image](https://user-images.githubusercontent.com/79651203/167407808-05c9d873-e392-4abc-ba97-8316fe4d109a.png)

**Comment by humpalum** [comment]
Thanks, 
fixed in https://github.com/humpalum/vscode-sigma/commit/f2bd04c23540e3db77c7070e8be80c0d57d82464

published in version 1.1.1 @marketplace
