### ISSUE TITLE
Bugs for "Unknown tag" in MITRE ATTACK tags

### ISSUE THREAD

**Issue by kmahyyg** [humpalum/vscode-sigma#12]
![20230716-005754-Code-004257@2x](https://github.com/humpalum/vscode-sigma/assets/16604643/cf3b7eab-37ed-4b2b-9081-8951efe98e1f)

check above, thanks.

**Comment by kmahyyg** [comment]
Sorry, my fault.

**Comment by humpalum** [comment]
So is this an issue now or not? 🙃

**Comment by kmahyyg** [comment]
not an issue, so sorry.
