### ISSUE TITLE
Add updated TLPs

### ISSUE THREAD

**Issue by HBadger0017** [humpalum/vscode-sigma#18]
How can I update the TLP tags for VSCode?  I want to add TLP:AMBER+STRICT to align with current first.org listings.

Thanks in advance.

**Comment by humpalum** [comment]
I think we would need to wait until the spec is updated and then change the extension accordingly

https://github.com/SigmaHQ/sigma-specification/issues/104

**Comment by humpalum** [comment]
I've added the TLP tags to the diagnostics in #5071ad1

For now, every tag with "tlp." will be allowed. 

This could be a stricter list. Feel free to make it more strict in `diagnostics.ts` . Currently its just a quick regex in line 209.
