### ISSUE TITLE
feat: Focus inside the quotes instead of after

### ISSUE THREAD

**Issue by phantinuss** [humpalum/vscode-sigma#2]
![image](https://user-images.githubusercontent.com/79651203/174579582-ceb4b599-15ca-4cbd-b96c-6ea24668cb69.png)
the extension helps by inserting a list entry with quotes if the user presses enter at the end of line of a list. It would be nice if the focus then is not outside the quotes but inside the quotes for easy pasting.

**Comment by humpalum** [comment]
Will be fixed in v1.3.1 once my Internet connection allows me to publish it. Thanks

**Comment by humpalum** [comment]
1.3.1 should be available on the marketplace.
