### ISSUE TITLE
Sigma v2 tags not found

### ISSUE THREAD

**Issue by 0xFustang** [humpalum/vscode-sigma#28]
## Description

When using the tags as per the Sigma v2 [specification](https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-tags-appendix.md#namespace-attack) with a `-` instead of `_` the tag is not found.

Example:

```
tags:
  - attack.t1110.003
  - attack.credential-access
  ```
  
  Would it be possible to have the tags system aligned with the spec? 🙏

**Comment by humpalum** [comment]
will be fixed in next release
