### ISSUE TITLE
sigmac not recognized. 

### ISSUE THREAD

**Issue by wadingthrulogs** [humpalum/vscode-sigma#3]
Trying to get the compile to work and I'm getting the error below.  Do I just need to add Sigmac as an environment variable or is there another step I'm missing with VScode? 

Error: Command failed: sigmac --config ~/sigma/tools/config/splunk-windows.yml --target splunk  /c:/Users/Wade/Desktop/proc_creation_win_clip.yml
'sigmac' is not recognized as an internal or external command,
operable program or batch file.
 --- 'sigmac' is not recognized as an internal or external command,
operable program or batch file.

Thanks,

**Comment by humpalum** [comment]
Currently it works by having installed sigmac globally. So it either needs to be in your Path variable somehow or you link it from directory that is in the Path variable. 

Feel free to ask if you need further help with this.

![image](https://user-images.githubusercontent.com/11175099/176852905-621d1343-c6c0-4801-93df-e9920e668229.png)

**Comment by saharshtapi** [comment]
@humpalum  can you elaborate on how to configure the settings
