### ISSUE TITLE
Invalid Mitre ID T1089

### ISSUE THREAD

**Issue by faisalusuf** [humpalum/vscode-sigma#7]
The extension is showing an invalid mitre ID T1089

https://attack.mitre.org/techniques/T1089
![image](https://user-images.githubusercontent.com/2043079/215347467-39f60bcc-753e-4bf3-a614-94d9c9013081.png)

Thanks.

**Comment by humpalum** [comment]
Thanks for opening the Issue!

I will be updating the Tags with the newest File from:
https://github.com/mitre/cti/blob/master/enterprise-attack/enterprise-attack.json

However, if the name is not fixed, which it doesn't seem to be, there is not much more i can do other than waiting for them to update the File.
